aws:
  dynamodb:
    endpoint: ${AWS_DYNAMODB_ENDPOINT:}
  regionName: ${AWS_REGION:us-east-1}
  accessKey: ${AWS_ACCESSKEY:}
  secretKey: ${AWS_SECRETKEY:}
spring:
  main:
    allow-bean-definition-overriding: true